onEvent('recipes', event => {
    event.remove({id: 'immersiveengineering:mineral/auricupride'})
    event.remove({id: 'immersiveengineering:mineral/ancient_debris'})
    event.remove({id: 'immersiveengineering:mineral/beryl'})
    event.remove({id: 'immersiveengineering:mineral/bituminous_coal'})
    event.remove({id: 'immersiveengineering:mineral/cassiterite'})
    event.remove({id: 'immersiveengineering:mineral/chalcopyrite'})
    event.remove({id: 'immersiveengineering:mineral/cinnabar'})
    event.remove({id: 'immersiveengineering:mineral/cooled_lava_tube'})
    event.remove({id: 'immersiveengineering:mineral/cooperite'})
    event.remove({id: 'immersiveengineering:mineral/galena'})
    event.remove({id: 'immersiveengineering:mineral/igneous_rock'})
    event.remove({id: 'immersiveengineering:mineral/laterite'})
    event.remove({id: 'immersiveengineering:mineral/mephitic_quarzite'})
    event.remove({id: 'immersiveengineering:mineral/nether_silt'})
    event.remove({id: 'immersiveengineering:mineral/pentlandite'})
    event.remove({id: 'immersiveengineering:mineral/silt'})
    event.remove({id: 'immersiveengineering:mineral/uraninite'})
    event.remove({id: 'immersiveengineering:mineral/wolframite'})
})